---
include: https://raw.githubusercontent.com/hassio-addons/organization/master/gitlabci/addon.yml

variables:
  ADDON_GITHUB_REPO: "shawly/hassio-api-scapegoat"
  ADDON_SLUG: "api-scapegoat"
  ADDON_TARGET: "api-scapegoat"

  ADDON_LEGACY_TAGS: "true"

  ADDON_AARCH64_BASE: "hassioaddons/base-aarch64:7.0.3"
  ADDON_AMD64_BASE: "hassioaddons/base-amd64:7.0.3"
  ADDON_ARMHF_BASE: "hassioaddons/base-armhf:7.0.3"
  ADDON_ARMV7_BASE: "hassioaddons/base-armv7:7.0.3"
  ADDON_I386_BASE: "hassioaddons/base-i386:7.0.3"

  ADDONS_REPO_STABLE: "shawly/hassio-addons"
  ADDONS_REPO_BETA: "shawly/hassio-addons-beta"
  ADDONS_REPO_EDGE: "shawly/hassio-addons-edge"

  DOCKER_HUB_ORG: shawly
  # skip shellcheck until api scapegoat is in it's own git repository
  PREFLIGHT_SHELLCHECK: "false"
